### ISSUE TITLE
Incompatible with other font mods

### ISSUE THREAD

**Issue by gimme** [liolok/TsangerXuansan#1]
Context: https://github.com/gimme/item-meta/issues/1

I think the current way the fonts are loaded makes it difficult to be compatible with other mods that play with fonts.

I did some research and found this [reference in the update notes](https://dontstarve.wiki.gg/wiki/Don%27t_Starve_Together/Version_History/2024#:~:text=Fonts%20are%20now%20safe%20to%20use%20TheSim%3ALoadFont%20multiple%20times%20it%20is%20advised%20to%20add%20your%20font%20to%20the%20GLOBAL.FONTS%20table%20with%20table.insert%20and%20call%20AddSimPostInit(GLOBAL.LoadFonts)%20with%20the%20appropriate%20Assets%20table%20definition%20in%20modmain%20to%20have%20your%20font%20asset%20loaded.). I guess that is the current recommended way to load them.

**Comment by liolok** [comment]
Should be fixed at [f7d0488](https://github.com/liolok/TsangerXuansan/commit/f7d0488a45a10e645e8c9e1e0e9c0e98f850a539)

**Comment by gimme** [comment]
Yep, that should do it. [Row 22](https://github.com/liolok/TsangerXuansan/commit/f7d0488a45a10e645e8c9e1e0e9c0e98f850a539#diff-d5bc176de0b47e51b89890fd0d6d4a0866ac7ddbe8558729fbcbf486a6d80a8bR22) is the key.
